-- In-game identifiers, used to import the player's zoo from the game's own data
-- (park.getAllParksOfUser JSON). The game names animals "animal_<noun>_<modifier>"
-- (e.g. animal_kangaroo_giant_red) and coats "<animal id>_<coat>" (animal_bat_ghost_black),
-- which do not map 1:1 to the wiki names, hence an explicit column.
-- Animals without a game_id fall back to an in-app strict word match at import time.
alter table public.animals add column if not exists game_id text unique;
alter table public.animal_variants add column if not exists game_id text unique;

-- Mapping verified against a real account (2026-10-07). Ambiguous picks were settled
-- by enclosure biome / scientific name (pig_bush = Red River Hog, buck_marsh = Sitatunga,
-- gnu_white_tailed = Black Wildebeest, waldrapp = Northern Bald Ibis, kangaroo_tree =
-- Goodfellow Tree Kangaroo, fox_red_cross = Mottled coat…).
update public.animals a set game_id = m.game_id from (values
  ('animal_aardvark', 'Aardvark'),
  ('animal_alpaca', 'Alpaca'),
  ('animal_anaconda_giant', 'Green Anaconda'),
  ('animal_armadillo', 'Armadillo'),
  ('animal_baboon', 'Baboon'),
  ('animal_badger', 'European Badger'),
  ('animal_bat_ghost', 'Ghost Bat'),
  ('animal_bear_black_american', 'American Black Bear'),
  ('animal_bear_kodiak', 'Kodiak Bear'),
  ('animal_bear_moon', 'Moon Bear'),
  ('animal_bear_polar', 'Polar Bear'),
  ('animal_beaver', 'Beaver'),
  ('animal_betta', 'Siamese Fighting Fish'),
  ('animal_bilby', 'Bilby'),
  ('animal_bison_american', 'American Bison'),
  ('animal_boar', 'Wild Boar'),
  ('animal_buck_marsh', 'Sitatunga'),
  ('animal_capuchin_white_faced', 'Panamanian White-Faced Capuchin'),
  ('animal_capybara', 'Capybara'),
  ('animal_cardinal_northern', 'Red Cardinal'),
  ('animal_cassowary_australian', 'Southern Cassowary'),
  ('animal_cat_marbled', 'Marbled Cat'),
  ('animal_chimpanzee', 'Chimpanzee'),
  ('animal_chinchilla_long_tailed', 'Long-Tailed Chinchilla'),
  ('animal_chipmunk_eastern', 'Eastern Chipmunk'),
  ('animal_cobra_indian', 'Indian Cobra'),
  ('animal_crocodile', 'Nile Crocodile'),
  ('animal_discus', 'Discus'),
  ('animal_dog_short_eared', 'Short-Eared Zorro'),
  ('animal_dolphin_irrawaddy', 'Irrawaddy Dolphin'),
  ('animal_donkey_afrikan', 'African Wild Ass'),
  ('animal_dormouse', 'Hazel Dormouse'),
  ('animal_duck_long_tailed', 'Long-Tailed Duck'),
  ('animal_duck_mandarin', 'Mandarin Duck'),
  ('animal_dugong', 'Dugong'),
  ('animal_eagle_bald', 'Bald Eagle'),
  ('animal_eagle_owl_philippine', 'Philippine Eagle Owl'),
  ('animal_elephant_african', 'African Elephant'),
  ('animal_elephant_borneo', 'Borneo Elephant'),
  ('animal_enchidna_short_beaked', 'Short-Beaked Echidna'),
  ('animal_fennec_fox', 'Fennec Fox'),
  ('animal_flamingo', 'Flamingo'),
  ('animal_fox_cape', 'Cape Fox'),
  ('animal_fox_polar', 'Arctic Fox'),
  ('animal_fox_red', 'Red Fox'),
  ('animal_frogmouth', 'Tawny Frogmouth'),
  ('animal_gaur', 'Gaur'),
  ('animal_genet_common', 'Common Genet'),
  ('animal_giraffe', 'Reticulated Giraffe'),
  ('animal_gnu_white_tailed', 'Black Wildebeest'),
  ('animal_goat', 'Domestic Goat'),
  ('animal_grouse_sage_greater', 'Greater Sage Grouse'),
  ('animal_hamster_european', 'European Hamster'),
  ('animal_harpy', 'Harpy Eagle'),
  ('animal_hippo', 'Hippopotamus'),
  ('animal_hoopoe_eurasian', 'Eurasian Hoopoe'),
  ('animal_horse', 'Horse'),
  ('animal_ibis_black_headed', 'Black-Headed Ibis'),
  ('animal_ibis_straw_necked', 'Straw-Necked Ibis'),
  ('animal_jerboa_long_eared', 'Long-Eared Jerboa'),
  ('animal_kangaroo_giant_red', 'Red Kangaroo'),
  ('animal_kangaroo_tree', 'Goodfellow Tree Kangaroo'),
  ('animal_koala', 'Koala'),
  ('animal_komodo_dragon', 'Komodo dragon'),
  ('animal_lemur_sclaters', 'Blue-Eyed Black Lemur'),
  ('animal_lion', 'Lion'),
  ('animal_lizard_armadilo', 'Armadillo Girdled Lizard'),
  ('animal_lizard_horned', 'Horned Lizard'),
  ('animal_loris_slow', 'Slow Loris'),
  ('animal_lynx', 'Lynx'),
  ('animal_macaque_japanese', 'Japanese Macaque'),
  ('animal_mangabey_golden_bellied', 'Golden-Bellied Mangabey'),
  ('animal_manta', 'Giant Oceanic Manta Ray'),
  ('animal_monitor_savanna', 'Savannah Monitor'),
  ('animal_monkey_long_nosed', 'Proboscis Monkey'),
  ('animal_moose', 'Moose'),
  ('animal_murre_common', 'Common Murre'),
  ('animal_nyala_mountain', 'Mountain Nyala'),
  ('animal_oarfish', 'Oarfish'),
  ('animal_okapi', 'Okapi'),
  ('animal_oriole_eurasian_golden', 'Eurasian Golden Oriole'),
  ('animal_oryx', 'Oryx'),
  ('animal_pony_shetland', 'Shetland Pony'),
  ('animal_iguana_galapagos_land_pink', 'Galápagos Pink Land Iguana'),
  ('animal_porcupine_crested', 'Crested Porcupine'),
  ('animal_lynx_canadian', 'Canadian Lynx'),
  ('animal_impala', 'Impala'),
  ('animal_peacock_pheasant_gray', 'Gray Peacock-Pheasant'),
  ('animal_jackal_striped', 'Black-Backed Jackal'),
  ('animal_oryx_scimitar', 'Scimitar Oryx'),
  ('animal_ostrich', 'Common Ostrich'),
  ('animal_owl_white_faced', 'White-Faced Owl'),
  ('animal_ozelot', 'Ocelot'),
  ('animal_pademelon_red_necked', 'Red-Necked Pademelon'),
  ('animal_panda_giant', 'Giant Panda'),
  ('animal_panda_red', 'Red Panda'),
  ('animal_panther', 'Panther'),
  ('animal_parrot', 'Scarlet Macaw'),
  ('animal_parrot_pesquet', 'Pesquet''s Parrot'),
  ('animal_peacock', 'Peafowl'),
  ('animal_peccarie', 'Collared Peccary'),
  ('animal_pedetes', 'Springhare'),
  ('animal_penguin_king', 'King Penguin'),
  ('animal_pig', 'Domestic Pig'),
  ('animal_pig_bush', 'Red River Hog'),
  ('animal_pigeon_crowned', 'Western Crowned Pigeon'),
  ('animal_pudu_northern', 'Northern Pudu'),
  ('animal_quoll', 'Quoll'),
  ('animal_rabbit', 'Rabbit'),
  ('animal_rabbit_lop', 'Lop Rabbit'),
  ('animal_rabbit_snow', 'Snow Hare'),
  ('animal_racoon_crab_eating', 'Crab-Eating Raccoon'),
  ('animal_rat_maned', 'Maned Rat'),
  ('animal_rhino_white', 'White Rhinoceros'),
  ('animal_sable', 'Sable'),
  ('animal_salamander_fire', 'Fire Salamander'),
  ('animal_sea_lion_south', 'Southern Sea Lion'),
  ('animal_seadragon_leafy', 'Leafy Seadragon'),
  ('animal_seal_leopard', 'Leopard Seal'),
  ('animal_secretarybird', 'Secretarybird'),
  ('animal_sengis_giant', 'Giant Sengi'),
  ('animal_serval', 'Serval'),
  ('animal_sheep', 'Sheep'),
  ('animal_sheep_snow', 'Snow Sheep'),
  ('animal_siamang', 'Siamang'),
  ('animal_skunk_spotted', 'Spotted Skunk'),
  ('animal_spoonbill_black_faced', 'Blacked-Faced Spoonbill'),
  ('animal_squid_vampire', 'Vampire Squid'),
  ('animal_surgeonfish_palette', 'Royal Blue Tang'),
  ('animal_tahr_arabian', 'Arabian Tahr'),
  ('animal_tahr_himalayan', 'Himalayan Tahr'),
  ('animal_tamaraw', 'Tamaraw'),
  ('animal_tanuki', 'Tanuki'),
  ('animal_tapir', 'Tapir'),
  ('animal_tegu_black_white', 'Argentine Black and White Tegu'),
  ('animal_tenrec_hedgehog_small', 'Lesser Hedgehog Tenrec'),
  ('animal_tenrec_lowland_streaked', 'Lowland Streaked Tenrec'),
  ('animal_tern_arctic', 'Arctic Tern'),
  ('animal_tortoise_leopard', 'Leopard Tortoise'),
  ('animal_toucan_giant', 'Toco Toucan'),
  ('animal_toucanet_saffron', 'Saffron Toucanet'),
  ('animal_turtle_giant', 'Giant Tortoise'),
  ('animal_turtle_snapper', 'Alligator Snapping Turtle'),
  ('animal_vulture_white_headed', 'White-Headed Vulture'),
  ('animal_waldrapp', 'Northern Bald Ibis'),
  ('animal_walrus', 'Walrus'),
  ('animal_weasel_least', 'Least Weasel'),
  ('animal_whale_bowhead', 'Bowhead Whale'),
  ('animal_wildcat_european', 'European Wildcat'),
  ('animal_wolf', 'Wolf'),
  ('animal_wolf_polar', 'Arctic Wolf'),
  ('animal_wombat_bare_nosed', 'Common Wombat'),
  ('animal_zebra_steppe', 'Plains Zebra')
) as m(game_id, name_en) where a.name_en = m.name_en;

update public.animal_variants v set game_id = m.game_id from (values
  ('animal_baboon_olive', 'Baboon', 'Olive'),
  ('animal_bat_ghost_black', 'Ghost Bat', 'Black'),
  ('animal_bear_black_american_blonde', 'American Black Bear', 'Blonde'),
  ('animal_discus_striped', 'Discus', 'Striped'),
  ('animal_fox_polar_black', 'Arctic Fox', 'Black'),
  ('animal_fox_red_cross', 'Red Fox', 'Mottled'),
  ('animal_goat_black', 'Domestic Goat', 'Black'),
  ('animal_goat_white', 'Domestic Goat', 'White'),
  ('animal_horse_drapple_gray', 'Horse', 'Dapple-Gray'),
  ('animal_kangaroo_tree_lumholtz', 'Goodfellow Tree Kangaroo', 'Lumholtz'),
  ('animal_koala_brown', 'Koala', 'Brown'),
  ('animal_oryx_arabian', 'Oryx', 'Arabian'),
  ('animal_panda_giant_brown', 'Giant Panda', 'Brown'),
  ('animal_penguin_king_yellow', 'King Penguin', 'Yellow'),
  ('animal_pig_brown', 'Domestic Pig', 'Brown'),
  ('animal_rabbit_black_white', 'Rabbit', 'Black & White'),
  ('animal_rabbit_lilac', 'Rabbit', 'Lilac'),
  ('animal_rabbit_lop_grey', 'Lop Rabbit', 'Gray'),
  ('animal_sheep_brown', 'Sheep', 'Brown'),
  ('animal_sheep_snow_white', 'Snow Sheep', 'White'),
  ('animal_sheep_spotted', 'Sheep', 'Spotted'),
  ('animal_toucan_giant_white', 'Toco Toucan', 'White'),
  ('animal_zebra_steppe_black', 'Plains Zebra', 'Black')
) as m(game_id, name_en, coat_name)
  join public.animals a on a.name_en = m.name_en
 where v.animal_id = a.id and v.coat_name = m.coat_name;
