-- Variant coats imported from the sheet (EN + FR). Catalog data.
insert into public.animal_variants (animal_id, coat_name, coat_name_fr)
select a.id, v.coat_name, nullif(v.coat_name_fr,'')
from public.animals a
join (values
  ('Ghost Bat','Black','noire'),
  ('American Hog-Nosed Skunk','Humboldt''s','de Humbolt'),
  ('Common Genet','Brown','brune'),
  ('Sable','White','blanche'),
  ('Sable','Red','rouge'),
  ('Jungle Cat','Black','Noir'),
  ('Cougar','White','Blanc'),
  ('King Penguin','Leucistic','Leuciste'),
  ('European Wildcat','Light','Clair'),
  ('Fallow Deer','White','Blanc'),
  ('Fallow Deer','Black','Noir'),
  ('Fallow Deer','Spotted','Tacheté'),
  ('Lop Rabbit','Gray','Gris'),
  ('Bearded Vulture','Red','Rouge'),
  ('Arctic Fox','Brown','brun'),
  ('Arctic Fox','Black','noir'),
  ('Red Ruffed Lemur','Black & White','Noir & Blanc'),
  ('Musk Deer','Gold','doré'),
  ('Oryx','Arabian','Arabique'),
  ('Oryx','Beisa','Beisa'),
  ('Arctic Wolf','Gray','noir'),
  ('Mandrill','White','blanc'),
  ('European Badger','Red','Rouge'),
  ('Ganges River Dolphin','Pink','rose'),
  ('Crested Porcupine','White','Blanc'),
  ('Whiptail Wallaby','Black','Noir'),
  ('Brushtail Possum','Brown','Brun'),
  ('Brushtail Possum','Yellow','Jaune'),
  ('Reindeer','White','Blanc'),
  ('Fishing Cat','Albino','Albinos'),
  ('Lar Gibbon','Black','noir'),
  ('Lynx','Light','Clair'),
  ('Toco Toucan','White','blanc'),
  ('American Black Bear','Blonde','Blond'),
  ('Coati','White-Nosed','Nez blanc'),
  ('Jaguarundi','Black','Noir'),
  ('Jaguarundi','Red','Rouge'),
  ('Komodo dragon','Blue','Bleu'),
  ('Alpaca','White','Blanc'),
  ('Alpaca','Black','Noir'),
  ('Alpaca','Spotted','Tacheté'),
  ('Nile Crocodile','White','blanc'),
  ('African Wild Dog','White','Blanc'),
  ('African Wild Dog','Brown','Brun'),
  ('African Wild Dog','Black','Noir'),
  ('Sumatran Tiger','White','Blanc'),
  ('Red Fox','Silver Fox','Argenté'),
  ('Red Fox','Leucistic','Leuciste'),
  ('Red Fox','Mottled','Tacheté'),
  ('Snow Hare','Summer','pelage d''été'),
  ('Swan','Black','noir'),
  ('Panther','Jaguar','jaguar'),
  ('Manatee','Black','noir'),
  ('Sulphur-Crested Cockatoo','White','blanc'),
  ('Roe Deer','Black','Noir'),
  ('Tapir','White','Blanc'),
  ('Goodfellow Tree Kangaroo','Lumholtz','Lumholtz'),
  ('Kiwi','Spotted','Tacheté'),
  ('Ferret Badger','Brown',''),
  ('Ferret Badger','Light-Brown',''),
  ('Shetland Pony','White','blanc'),
  ('Shetland Pony','Brown','Brun'),
  ('Shetland Pony','Black & White','Noir et blanc'),
  ('Mountain Gorilla','Whilte','blanc'),
  ('Bald Eagle','Leucistic','Leuciste'),
  ('Capybara','Black','Noir'),
  ('Hippopotamus','Pink','Rose'),
  ('Bengal Tiger','White','blanc'),
  ('Reticulated Giraffe','Black','Noire'),
  ('African Elephant','Leucistic','Leuciste'),
  ('Wolf','Red','Rouge'),
  ('Plains Zebra','White','Blanc'),
  ('Plains Zebra','Black','Noir'),
  ('Moose','White Moose','Blanc'),
  ('Moose','Piebald','Tacheté'),
  ('Giant Panda','Brown','Brun'),
  ('Common Ostrich','Brown','Brune'),
  ('Peafowl','Leucistic','Leucistique'),
  ('Peafowl','Piebald','Tacheté'),
  ('Kodiak Bear','Blonde','Blond'),
  ('Kodiak Bear','Drak','Foncé'),
  ('Lion','White','Blanc'),
  ('Koala','Brown','Roux'),
  ('Domestic Goat','White','Blanche'),
  ('Domestic Goat','Black','Noir'),
  ('Pacman Frog','Brown','brune'),
  ('Sheep','Brown','Brun'),
  ('Sheep','Mioget','Mioget'),
  ('Sheep','Spotted','Tacheté'),
  ('Rabbit','Albino','Albinos'),
  ('Rabbit','Black & White','Noir & Blanc'),
  ('Rabbit','Gray','petit-gris'),
  ('Rabbit','Valentine''s Day','Saint-Valentin'),
  ('Rabbit','Spotted','Tacheté'),
  ('Rabbit','Harlequin','Tigré'),
  ('Wild Boar','White','Blanc'),
  ('Flamingo','White','Blanc'),
  ('Flamingo','Black','Noir'),
  ('Horse','Black','Noir'),
  ('Horse','Pinto','Pinto'),
  ('Horse','Dapple-Gray','Pommelé'),
  ('Red Kangaroo','White','Blanc'),
  ('Domestic Pig','Brown','Brun')
) as v(base_en, coat_name, coat_name_fr) on a.name_en = v.base_en
on conflict (animal_id, coat_name) do update set coat_name_fr = excluded.coat_name_fr;
